[db]
dir = "./data/db/feeds"

[data]
path = "."

[log]
level = "debug"

[app]
mode = "dev"
sleep = 25

[http.get]
timeout = 10
retries = 0

[http.head]
timeout = 5
retries = 2
wait = 100

[time]
timezone = "America/Mexico_City"